version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"       # Порт для FastAPI
    volumes:
      - ./backend:/app    # Монтируем локальную папку с бэкендом в контейнер
      - ./model:/app/model # Монтируем локальную папку с моделями в контейнер
    networks:
      - app-network
#    environment:
#      - UVICORN_CMD="uvicorn app:app --host 0.0.0.0 --port 8000 --reload" # Настройка для Uvicorn
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"       # Порт для фронтенда
    volumes:
      - ./frontend:/app   # Монтируем локальную папку с фронтендом в контейнер
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
